# Generated by Django 5.1.1 on 2024-09-19 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='contact',
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='anon_', max_length=25, unique=True),
        ),
    ]
