# Generated by Django 5.1.1 on 2024-09-19 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_user', '0002_remove_user_contact_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
