# Generated by Django 5.1.1 on 2024-10-14 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_remove_recipe_name_recipe_created_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default='recipes/default_food.png', upload_to=''),
        ),
    ]
