# Generated by Django 5.1.2 on 2024-11-18 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0009_alter_recipe_ingredients'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='procedure',
            new_name='procedures',
        ),
    ]
