# Generated by Django 5.1.2 on 2024-11-19 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0010_rename_procedure_recipe_procedures'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='ingredients_count',
            field=models.IntegerField(default='1'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.CharField(default='No Input', max_length=255),
        ),
    ]
