# Generated by Django 5.1.2 on 2024-11-19 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0011_recipe_ingredients_count_alter_recipe_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients_count',
            field=models.CharField(default='1', max_length=255),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='procedures',
            field=models.CharField(default='No Input', max_length=1000),
        ),
    ]
