# Generated by Django 5.1.2 on 2024-11-19 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0013_alter_recipe_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients_count',
            field=models.TextField(default='1'),
        ),
    ]
