# Generated by Django 5.1.1 on 2024-11-19 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0004_alter_recipe_image'),
        ('recipe', '0014_alter_recipe_ingredients_count'),
    ]

    operations = [
    ]
