# Generated by Django 5.1.2 on 2024-11-25 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0017_alter_recipe_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='procedures',
            field=models.TextField(default='No Input'),
        ),
    ]
