# Generated by Django 5.1.2 on 2024-11-30 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0018_alter_recipe_procedures'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='total_reviews',
            field=models.IntegerField(default=0),
        ),
    ]
