# Generated by Django 5.1.2 on 2024-12-01 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0022_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
