# Generated by Django 5.1.1 on 2024-12-03 12:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0002_recipereport_userreport'),
        ('recipe', '0025_comment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipereport',
            old_name='reporter',
            new_name='reporter_id',
        ),
        migrations.RenameField(
            model_name='userreport',
            old_name='reporter',
            new_name='reporter_id',
        ),
        migrations.AlterUniqueTogether(
            name='recipereport',
            unique_together={('reporter_id', 'recipe_id')},
        ),
        migrations.AlterUniqueTogether(
            name='userreport',
            unique_together={('reporter_id', 'user_id')},
        ),
    ]
