# Generated by Django 5.1.1 on 2024-12-03 13:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0003_rename_reporter_recipereport_reporter_id_and_more'),
        ('recipe', '0025_comment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipereport',
            old_name='reporter_id',
            new_name='reporter',
        ),
        migrations.RenameField(
            model_name='userreport',
            old_name='reporter_id',
            new_name='reporter',
        ),
        migrations.AlterUniqueTogether(
            name='recipereport',
            unique_together={('reporter', 'recipe_id')},
        ),
        migrations.AlterUniqueTogether(
            name='userreport',
            unique_together={('reporter', 'user_id')},
        ),
    ]
